[workspace]

members = [
  "test",
  "aggregator",
  "backyard",
  "collections",
  "guessing_game",
  "rectangles",
  "restaurant",
  "variables",
  "minigrep",
  "closure",
  "smart_pointer", "limit_tracker",
]
resolver = "3"
